interface Product {
    id: number;
    name: string;
    category: string;
    price: number;
}

export const ALL_PRODUCTS: Product[] = [
    // Electrónica
    { id: 1, name: 'Laptop Pro 13"', category: 'Electrónica', price: 1200 },
    { id: 2, name: 'Teclado Mecánico RGB', category: 'Electrónica', price: 90 },
    { id: 3, name: 'Mouse Inalámbrico Ergonómico', category: 'Electrónica', price: 45 },
    { id: 4, name: 'Monitor 27" 4K', category: 'Electrónica', price: 550 },
    { id: 5, name: 'Auriculares Bluetooth Cancelación Ruido', category: 'Electrónica', price: 150 },
    { id: 6, name: 'Webcam HD 1080p', category: 'Electrónica', price: 75 },
    { id: 7, name: 'Disco Duro Externo 2TB', category: 'Electrónica', price: 80 },
    { id: 8, name: 'Altavoces de Escritorio 2.1', category: 'Electrónica', price: 110 },
    { id: 9, name: 'Tablet 10"', category: 'Electrónica', price: 300 },
    { id: 10, name: 'Smartwatch Fitness', category: 'Electrónica', price: 120 },
    { id: 11, name: 'Cable HDMI 2.1', category: 'Electrónica', price: 15 },
    { id: 12, name: 'Router WiFi 6', category: 'Electrónica', price: 140 },
    { id: 13, name: 'Micrófono USB para Streaming', category: 'Electrónica', price: 95 },
    { id: 14, name: 'Cargador Rápido USB-C', category: 'Electrónica', price: 25 },
    { id: 15, name: 'Drone con Cámara 4K', category: 'Electrónica', price: 850 },
    { id: 16, name: 'Ebook Reader', category: 'Electrónica', price: 180 },
    { id: 17, name: 'Smart TV 55" OLED', category: 'Electrónica', price: 1500 },
    { id: 18, name: 'Proyector Portátil', category: 'Electrónica', price: 250 },
    { id: 19, name: 'Batería Externa 20000mAh', category: 'Electrónica', price: 40 },
    { id: 20, name: 'Tarjeta Gráfica RTX 4080', category: 'Electrónica', price: 1100 },
    { id: 21, name: 'Laptop Pro 15"', category: 'Electrónica', price: 1450 },
    { id: 22, name: 'Teclado Inalámbrico Slim', category: 'Electrónica', price: 70 },
    { id: 23, name: 'Mouse Gamer RGB', category: 'Electrónica', price: 60 },
    { id: 24, name: 'Auriculares In-Ear Deportivos', category: 'Electrónica', price: 55 },
    { id: 25, name: 'Disco Duro SSD 1TB', category: 'Electrónica', price: 100 },

    // Muebles
    { id: 26, name: 'Silla Ergonómica Pro', category: 'Muebles', price: 300 },
    { id: 27, name: 'Escritorio Ajustable en Altura', category: 'Muebles', price: 500 },
    { id: 28, name: 'Lámpara de Escritorio LED', category: 'Muebles', price: 60 },
    { id: 29, name: 'Estantería de Pared Modular', category: 'Muebles', price: 150 },
    { id: 30, name: 'Sillón de Oficina Ejecutivo', category: 'Muebles', price: 420 },
    { id: 31, name: 'Mesa Auxiliar de Centro', category: 'Muebles', price: 85 },
    { id: 32, name: 'Armario de 2 Puertas', category: 'Muebles', price: 250 },
    { id: 33, name: 'Cama Queen Size', category: 'Muebles', price: 650 },
    { id: 34, name: 'Mesa de Comedor Redonda', category: 'Muebles', price: 480 },
    { id: 35, name: 'Silla de Comedor de Madera (unidad)', category: 'Muebles', price: 70 },
    { id: 36, name: 'Sofá de 3 Plazas', category: 'Muebles', price: 750 },
    { id: 37, name: 'Mesa de Noche con Cajón', category: 'Muebles', price: 95 },
    { id: 38, name: 'Estantería para Libros Alta', category: 'Muebles', price: 180 },
    { id: 39, name: 'Silla Plegable', category: 'Muebles', price: 30 },
    { id: 40, name: 'Escritorio de Esquina', category: 'Muebles', price: 350 },
    { id: 41, name: 'Silla Ergonómica Básica', category: 'Muebles', price: 180 },
    { id: 42, name: 'Lámpara de Pie para Sala', category: 'Muebles', price: 120 },
    { id: 43, name: 'Cajonera de 4 Cajones', category: 'Muebles', price: 160 },
    { id: 44, name: 'Mesa de Centro de Cristal', category: 'Muebles', price: 210 },
    { id: 45, name: 'Sillón Reclinable', category: 'Muebles', price: 580 },

    // Libros
    { id: 46, name: 'Libro de Cocina Mediterránea', category: 'Libros', price: 25 },
    { id: 47, name: 'Novela Histórica: El último Reino', category: 'Libros', price: 20 },
    { id: 48, name: 'Manual de Programación en JavaScript', category: 'Libros', price: 40 },
    { id: 49, name: 'Libro de Poesía Clásica', category: 'Libros', price: 18 },
    { id: 50, name: 'Biografía de Steve Jobs', category: 'Libros', price: 30 },
    { id: 51, name: 'Libro Infantil de Cuentos', category: 'Libros', price: 15 },
    { id: 52, name: 'Atlas del Mundo', category: 'Libros', price: 55 },
    { id: 53, name: 'Libro de Fotografía Avanzada', category: 'Libros', price: 45 },
    { id: 54, name: 'Novela de Ciencia Ficción: Mundos Paralelos', category: 'Libros', price: 22 },
    { id: 55, name: 'Guía de Jardinería Urbana', category: 'Libros', price: 28 },
    { id: 56, name: 'Libro de Cocina Vegana', category: 'Libros', price: 27 },
    { id: 57, name: 'Manual de Diseño Gráfico', category: 'Libros', price: 35 },
    { id: 58, name: 'Libro de Misterio: La Sombra del Detective', category: 'Libros', price: 20 },
    { id: 59, name: 'Novela de Romance: Amor en París', category: 'Libros', price: 19 },
    { id: 60, name: 'Enciclopedia de Animales', category: 'Libros', price: 60 },

    // Deportes y Fitness
    { id: 61, name: 'Mancuernas Ajustables (par)', category: 'Deportes y Fitness', price: 120 },
    { id: 62, name: 'Esterilla de Yoga Premium', category: 'Deportes y Fitness', price: 35 },
    { id: 63, name: 'Bandas de Resistencia (set)', category: 'Deportes y Fitness', price: 25 },
    { id: 64, name: 'Bicicleta Estática', category: 'Deportes y Fitness', price: 400 },
    { id: 65, name: 'Cinta de Correr Plegable', category: 'Deportes y Fitness', price: 600 },
    { id: 66, name: 'Botella de Agua de Acero Inoxidable', category: 'Deportes y Fitness', price: 18 },
    { id: 67, name: 'Kit de Entrenamiento en Suspensión', category: 'Deportes y Fitness', price: 50 },
    { id: 68, name: 'Pelota de Pilates', category: 'Deportes y Fitness', price: 15 },
    { id: 69, name: 'Comba de Velocidad Ajustable', category: 'Deportes y Fitness', price: 12 },
    { id: 70, name: 'Rodillo de Espuma para Masaje', category: 'Deportes y Fitness', price: 20 },
    { id: 71, name: 'Bicicleta de Montaña', category: 'Deportes y Fitness', price: 700 },
    { id: 72, name: 'Saco de Boxeo', category: 'Deportes y Fitness', price: 90 },
    { id: 73, name: 'Guantes de Gimnasio', category: 'Deportes y Fitness', price: 25 },
    { id: 74, name: 'Reloj Deportivo GPS', category: 'Deportes y Fitness', price: 200 },
    { id: 75, name: 'Barra de Dominadas para Puerta', category: 'Deportes y Fitness', price: 40 },

    // Hogar y Cocina
    { id: 76, name: 'Juego de Sartenes Antiadherentes', category: 'Hogar y Cocina', price: 80 },
    { id: 77, name: 'Cafetera de Goteo Programable', category: 'Hogar y Cocina', price: 65 },
    { id: 78, name: 'Batidora de Vaso de Alta Potencia', category: 'Hogar y Cocina', price: 110 },
    { id: 79, name: 'Aspiradora sin Cable', category: 'Hogar y Cocina', price: 250 },
    { id: 80, name: 'Robot de Cocina Multifunción', category: 'Hogar y Cocina', price: 380 },
    { id: 81, name: 'Set de Cuchillos de Chef', category: 'Hogar y Cocina', price: 70 },
    { id: 82, name: 'Tostadora de 2 Rebanadas', category: 'Hogar y Cocina', price: 35 },
    { id: 83, name: 'Juego de Toallas de Baño', category: 'Hogar y Cocina', price: 50 },
    { id: 84, name: 'Vajilla de Porcelana (4 personas)', category: 'Hogar y Cocina', price: 95 },
    { id: 85, name: 'Horno de Microondas', category: 'Hogar y Cocina', price: 120 },
    { id: 86, name: 'Juego de Ollas y Cacerolas', category: 'Hogar y Cocina', price: 150 },
    { id: 87, name: 'Difusor de Aromas Ultrasónico', category: 'Hogar y Cocina', price: 45 },
    { id: 88, name: 'Plancha de Ropa a Vapor', category: 'Hogar y Cocina', price: 60 },
    { id: 89, name: 'Juego de Utensilios de Cocina', category: 'Hogar y Cocina', price: 25 },
    { id: 90, name: 'Termo para Café', category: 'Hogar y Cocina', price: 20 },
    { id: 91, name: 'Freidora de Aire', category: 'Hogar y Cocina', price: 85 },
    { id: 92, name: 'Máquina de Hacer Pan', category: 'Hogar y Cocina', price: 140 },
    { id: 93, name: 'Exprimidor de Cítricos', category: 'Hogar y Cocina', price: 30 },
    { id: 94, name: 'Escurridor de Platos', category: 'Hogar y Cocina', price: 40 },
    { id: 95, name: 'Juego de Copas de Vino', category: 'Hogar y Cocina', price: 55 },
    { id: 96, name: 'Juego de Sábanas de Algodón', category: 'Hogar y Cocina', price: 75 },
    { id: 97, name: 'Abridor de Vino Eléctrico', category: 'Hogar y Cocina', price: 25 },
    { id: 98, name: 'Set de Contenedores de Alimentos', category: 'Hogar y Cocina', price: 35 },
    { id: 99, name: 'Dispensador de Jabón Automático', category: 'Hogar y Cocina', price: 22 },
    { id: 100, name: 'Báscula de Cocina Digital', category: 'Hogar y Cocina', price: 28 },
];